// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from 'prisma/config';
import { loadEnvFile } from './env.js';

loadEnvFile('.env');

const useLocal = process.env.DB_TARGET === 'local';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env(useLocal ? 'LOCAL_DATABASE_URL' : 'DATABASE_URL'),
  },
});
